# -*- coding: utf-8 -*-
"""scrapper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u23K_y1nWdql1-ioPjuQ8lXINP91fzOx
"""
import sys
import metadata_parser

url = sys.argv[1]

page = metadata_parser.MetadataParser(url)
data = str(page.metadata)
D = data.replace("'","\"")
print(D)